services:
  backend:
    build:
      context: ./backend
    ports:
      - "8100:8100"
    environment:
      - MODEL_PATH=/app/model/model.pkl
    volumes:
      - ./backend/model:/app/model

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8100
    depends_on:
      - backend